spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}


app:
  jwt:
    # Cambia este secreto en producción (usa una variable de entorno, no lo dejes hardcodeado en el repo).
    # Debe tener al menos 32 caracteres para HS256.
    secret: "cambia-este-secreto-por-uno-largo-y-aleatorio-de-al-menos-32-caracteres"
    expiration-ms: 86400000 # 24 horas

  admin:
    email: ${SPRING_AUTH_USERNAME}
    password: ${SPRING_AUTH_PASSWORD}
    nombre: ${SPRING_AUTH_NAME}
